name: mysecond-pipeline

on: 
  push:
    branches: ["main"]

jobs:
    compile-the-code:
      runs-on: ubuntu-latest
      steps:
        - name: checkout the code
          uses: actions/checkout@v6
        - name: setup java
          uses: actions/setup-java@v5
          with:
             distribution: 'temurin'
             java-version: '25'
             cache: 'maven'
        - name: compile the code
          run: mvn compile
    test-the-code:
      needs: compile-the-code  
      runs-on: ubuntu-latest
      steps: 
        - name: checkout
          uses: actions/checkout@v6
        # - name: setup java
        #   uses: actions/setup-java@v5
        #   with:
        #      distribution: 'temurin'
        #      java-version: '25'
        #      cache: 'maven'
        - name: test the code
          run: mvn test
    package-the-code:
      needs: test-the-code
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v6
        - name: package the code
          run: mvn clean package                             
    docker-build-push:
        needs: package-the-code
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6

            - name: package
              run: mvn clean package   

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-south-1 
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: |
                  ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest
                  ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}  