name: mysecond-pipeline

on: 
  push:
    branches: ["main"]

jobs:
    compile-the-code:
      runs-on: ubuntu-latest
      steps:
        - name: checkout the code
          uses: actions/checkout@v6
        - name: setup java
          uses: actions/setup-java@v5
          with:
             distribution: 'temurin'
             java-version: '25'
             cache: 'maven'
        - name: compile the code
          run: mvn compile
    test-the-code:
      needs: compile-the-code  
      runs-on: ubuntu-latest
      steps: 
        - name: checkout
          uses: actions/checkout@v6
        # - name: setup java
        #   uses: actions/setup-java@v5
        #   with:
        #      distribution: 'temurin'
        #      java-version: '25'
        #      cache: 'maven'
        - name: test the code
          run: mvn test
    package-the-code:
      needs: test-the-code
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v6
        - name: package the code
          run: mvn clean package                             
    build-with-docker:
      needs: package-the-code
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v6
        - name: package
          run: mvn clean package  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v4 
        - name: build with docker
          run: docker build -t betapp:latest .

